export enum Attacker {
  Sledge = 'Sledge',
  Thatcher = 'Thatcher',
  Ash = 'Ash',
  Thermite = 'Thermite',
  Twitch = 'Twitch',
  Montagne = 'Montagne',
  Glaz = 'Glaz',
  Fuze = 'Fuze',
  Blitz = 'Blitz',
  IQ = 'IQ',
  Buck = 'Buck',
  Blackbeard = 'Blackbeard',
  Capitão = 'Capitão',
  Hibana = 'Hibana',
  Jackal = 'Jackal',
  Ying = 'Ying',
  Zofia = 'Zofia',
  Dokkaebi = 'Dokkaebi',
  Lion = 'Lion',
  Finka = 'Finka',
  Recruit = 'Recruit'
}
