export enum Defender {
  Smoke = 'Smoke',
  Mute = 'Mute',
  Castle = 'Castle',
  Pulse = 'Pulse',
  Doc = 'Doc',
  Rook = 'Rook',
  Kapkan = 'Kapkan',
  Tachanka = 'Tachanka',
  Jäger = 'Jäger',
  Bandit = 'Bandit',
  Frost = 'Frost',
  Valkyrie = 'Valkyrie',
  Caveira = 'Caveira',
  Echo = 'Echo',
  Mira = 'Mira',
  Lesion = 'Lesion',
  Ela = 'Ela',
  Vigil = 'Vigil',
  Maestro = 'Maestro',
  Alibi = 'Alibi',
  Recruit = 'Recruit'
}
