// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReactReduxSignalRDemo.Models;

namespace ReactReduxSignalRDemo.Migrations.Users
{
    [DbContext(typeof(UsersContext))]
    [Migration("20180814010457_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReactReduxSignalRDemo.Models.Stats", b =>
                {
                    b.Property<int>("StatsId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Deaths");

                    b.Property<int>("Kills");

                    b.Property<int>("Losses");

                    b.Property<string>("Rank");

                    b.Property<string>("TopAttacker");

                    b.Property<string>("TopDefender");

                    b.Property<int>("UserId");

                    b.Property<int>("Wins");

                    b.HasKey("StatsId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Stats");

                    b.HasData(
                        new { StatsId = 1, Deaths = 640, Kills = 1462, Losses = 124, Rank = "Gold One", TopAttacker = "Twitch", TopDefender = "Lesion", UserId = 1, Wins = 384 }
                    );
                });

            modelBuilder.Entity("ReactReduxSignalRDemo.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserId = 1, Username = "Chad" }
                    );
                });

            modelBuilder.Entity("ReactReduxSignalRDemo.Models.Stats", b =>
                {
                    b.HasOne("ReactReduxSignalRDemo.Models.User")
                        .WithOne("Stats")
                        .HasForeignKey("ReactReduxSignalRDemo.Models.Stats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
